import { css } from '@kuma-ui/core';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { KumaRegistry } from '@kuma-ui/next-plugin/registry';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" style={{ height: '100%' }}>
      <body
        className={inter.className}
        style={{
          height: '100%',
        }}
      >
        <KumaRegistry>{children}</KumaRegistry>
      </body>
    </html>
  );
}
